name: Sync engine from private release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'   # 每6小时同步一次，可改

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest release asset url
        env:
          GH_TOKEN: ${{ secrets.ENGINE_READ_TOKEN }}
        run: |
          set -e
          owner_repo="enxpower/ems-engine"
          asset_name="core-browser.js"
          api="https://api.github.com/repos/$owner_repo/releases/latest"
          url=$(curl -s -H "Authorization: token $GH_TOKEN" "$api" | jq -r ".assets[] | select(.name==\"$asset_name\").browser_download_url")
          if [ -z "$url" ] || [ "$url" = "null" ]; then
            echo "No $asset_name in latest release"; exit 1; fi
          mkdir -p modules
          curl -L -H "Authorization: token $GH_TOKEN" -o modules/core.js "$url"

      - name: Commit if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "engine-sync-bot"
            git config user.email "bot@users.noreply.github.com"
            git add modules/core.js
            git commit -m "chore: sync engine core.js from private release"
            git push
          else
            echo "No changes."
          fi
