name: Sync engine from private release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # 每6小时拉一次，可改
  push:
    branches: [ main ]
    paths:
      - .github/workflows/sync-engine.yml
permissions:
  contents: write   # ← 允许 actions 对仓库内容有写权限
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest release asset url
        id: rel
        env:
          GH_TOKEN: ${{ secrets.ENGINE_READ_TOKEN }}
        run: |
          owner_repo="enxpower/ems-engine"
          url=$(gh api repos/$owner_repo/releases/latest --jq '.assets[] | select(.name=="core-browser.js") | .browser_download_url')
          if [ -z "$url" ]; then echo "No core-browser.js in latest release"; exit 1; fi
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Download core-browser.js → modules/core.js
        run: |
          mkdir -p modules
          curl -H "Authorization: token ${{ secrets.ENGINE_READ_TOKEN }}" -L "${{ steps.rel.outputs.url }}" -o modules/core.js

      - name: Commit if changed
        run: |
          git config user.name "engine-sync-bot"
          git config user.email "bot@users.noreply.github.com"
          git add modules/core.js
          git diff --cached --quiet || git commit -m "chore: sync engine core.js from private release"
          git push
