name: Sync private engine → public vendor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Checkout private engine repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ENGINE_REPO || 'your-org/ems-engine' }}
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: _engine

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build engine (ESM)
        working-directory: _engine
        run: |
          npm ci
          npm run build
          ls -la dist

      - name: Copy artifact → vendor/core.esm.js
        run: |
          mkdir -p vendor
          # 私库构建产物：dist/core-browser.js（见下方私库 build）
          cp _engine/dist/core-browser.js vendor/core.esm.js

      - name: Normalize manifest paths (force relative to repo root)
        run: |
          jq '.modules.core="./vendor/core.esm.js"' modules/manifest.json > modules/manifest.json.tmp
          mv modules/manifest.json.tmp modules/manifest.json

      - name: Stamp engine version into footer
        run: |
          REV=$(git -C _engine rev-parse --short HEAD || echo "-")
          DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          # 将版本信息写入一个 JSON 文件，供 loader.js 读取备用（也可由引擎导出）
          mkdir -p vendor
          echo "{\"rev\":\"$REV\",\"builtAt\":\"$DATE\"}" > vendor/build.json

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vendor modules
          git commit -m "chore: sync engine $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
