name: Sync private engine → public vendor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

env:
  # 优先使用仓库“Variables”里配置的 ENGINE_REPO（例如 enxpower/ems-engine）
  # 若未配置，则默认使用 <当前仓库Owner>/ems-engine
  ENGINE_REPO_FALLBACK: ${{ format('{0}/ems-engine', github.repository_owner) }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      # 显式校验 Secret 是否存在，防止空值导致后续 checkout 报 "token not supplied"
      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.ENGINE_READ_TOKEN }}" ]; then
            echo "::error::Missing secret ENGINE_READ_TOKEN. Create a PAT with 'repo' scope and add as repository secret."
            exit 1
          fi

      - name: Resolve ENGINE_REPO
        id: repo
        run: |
          REPO="${{ vars.ENGINE_REPO }}"
          if [ -z "$REPO" ]; then
            REPO="${{ env.ENGINE_REPO_FALLBACK }}"
          fi
          echo "repo=$REPO" >> $GITHUB_OUTPUT

      - name: Checkout private engine repo
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.repo.outputs.repo }}
          token: ${{ secrets.ENGINE_READ_TOKEN }}
          path: _engine

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build engine (ESM)
        working-directory: _engine
        run: |
          npm ci
          npm run build
          ls -la dist

      - name: Copy artifact → vendor/core.esm.js
        run: |
          mkdir -p vendor
          # 私库产物：请确保构建生成 dist/core-browser.js
          cp _engine/dist/core-browser.js vendor/core.esm.js

      - name: Normalize manifest paths (force relative)
        run: |
          jq '.modules.core="./vendor/core.esm.js"' modules/manifest.json > modules/manifest.json.tmp
          mv modules/manifest.json.tmp modules/manifest.json

      - name: Stamp engine version into footer
        run: |
          REV=$(git -C _engine rev-parse --short HEAD || echo "-")
          DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          mkdir -p vendor
          echo "{\"rev\":\"$REV\",\"builtAt\":\"$DATE\"}" > vendor/build.json

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vendor modules
          git commit -m "chore: sync engine $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
