name: Sync engine to vendor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'   # 每 6 小时同步一次，可按需调整

permissions:
  contents: write            # 允许向公库提交

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Checkout private engine
        uses: actions/checkout@v4
        with:
          repository: enxpower/ems-engine        # ← 替换为你的私库
          token: ${{ secrets.ENGINE_READ_TOKEN }} # ← 公库里配置好的 PAT
          ref: main                               # 私库分支名
          path: _engine

      - name: Copy build artifacts
        run: |
          mkdir -p vendor modules
          # 优先 IIFE（<script> 直接用），其次 ESM，最后是 modules 目录
          if [ -f _engine/dist/ems-engine.iife.min.js ]; then
            cp _engine/dist/ems-engine.iife.min.js vendor/ems-engine.iife.min.js
          fi
          if [ -f _engine/dist/ems-engine.esm.js ]; then
            cp _engine/dist/ems-engine.esm.js vendor/ems-engine.esm.js
          fi
          if [ -d _engine/modules ]; then
            rm -rf modules && cp -r _engine/modules ./modules
          fi

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vendor modules
          git commit -m "chore: sync engine $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
